### ISSUE TITLE
Fatal Error in PHP7

### ISSUE THREAD

**Issue by rynaldos-zz** [woothemes/woosidebars-sbm-converter#1]
Here: https://github.com/woothemes/woosidebars-sbm-converter/blob/master/classes/class-woosidebars-sbm-converter.php#L399 we use `continue` outside a loop, which is illegal. This causes a `PHP Fatal error: 'continue' not in the 'loop' or 'switch' context` error in PHP7.

We should replace `continue` with `return` on line 399

Cheers! 

@mattyza @jeffikus

**Comment by jeffikus** [comment]
Thanks @rspublishing - i'll test and merge this over the weekend. Super low priority plugin, so I haven't had time to tackle this week yet.
